version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: messenger-postgres
    restart: always
    environment:
      POSTGRES_DB: messenger_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - messenger_postgres_data:/var/lib/postgresql/data

volumes:
  messenger_postgres_data: