server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/social-network
keycloak:
  server-uri: http://localhost:8080
  realm: social-network
  client-id: auth-service
  client-secret: BR2WbAzpXUYRM5aY5DU6nkufF3py80Q9
  admin-username: admin
  admin-password: admin