version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: personal-cabinet-postgres
    restart: always
    environment:
      POSTGRES_DB: personal-cabinet-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - personal_cabinet_db:/var/lib/postgresql/data

volumes:
  personal_cabinet_db: